### PR TITLE
Add ingress dns check

### PR DESCRIPTION
**Pull request by simongottschlag**

### CODE REVIEW

**Comment by phillebaba** [comment]
Good thing to check. I am just a bit worried what the effect on conntrack table overflow this will have. Could you just add a comment over the function to make sure that we verify that we do not get any issues. Other than that this should be fine.

**Comment by simongottschlag** [comment]
@phillebaba what about a cache? I see options of:

- Cache in Checker
- Global cache for all checks
- Global cache per function

If we add the cache to Checker, we either need to pass it as an argument to each check or make the checks methods of Checker.

I'm already trying to do a check where it verifies the txt records that they have the correct owner (external-dns) and I need a cache for it to not have to iterate the graph on each check.

**Comment by simongottschlag** [comment]
After thinking about this a bit, a higher order function should most likely suffice and be the easiest for now. I'll try it and get back to you.

**Comment by simongottschlag** [comment]
@phillebaba I've added a cache and (hopefully) forced DNS queries to go over TCP. WDYT?

**Comment by simongottschlag** [comment]
@phillebaba I've now refactored the check to use a single TCP connection for all lookups in the function. This is based on feedback from @bittrance :1st_place_medal:

**Review by phillebaba — APPROVED** [review]
LGTM

**Pull request merged**
